package tech.tabrita.com.ui.screens.profile

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.DarkMode
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Notifications
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.material3.windowsizeclass.WindowWidthSizeClass
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.layout.wrapContentWidth
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.ui.res.stringResource
import tech.tabrita.com.ui.theme.TaBritaDimens
import tech.tabrita.com.ui.theme.TaBritaColors
import tech.tabrita.com.R

// BuildConfig not generated by default; use hardcoded version for now
private const val APP_VERSION = "1.0.0"

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ProfileScreen(windowSizeClass: androidx.compose.material3.windowsizeclass.WindowSizeClass? = null) {
    var isDarkMode by remember { mutableStateOf(true) }
    var notificationsEnabled by remember { mutableStateOf(true) }

    val widthSizeClass = windowSizeClass?.widthSizeClass ?: WindowWidthSizeClass.Compact
    val isExpanded = widthSizeClass == WindowWidthSizeClass.Expanded
    val avatarSize = if (isExpanded) TaBritaDimens.avatarSize * 1.3f else TaBritaDimens.avatarSize
    val contentMaxWidth = if (isExpanded) TaBritaDimens.maxContentWidth else TaBritaDimens.maxContentWidth * 0.95f
    val horizontalPad = if (isExpanded) TaBritaDimens.paddingXXLarge else TaBritaDimens.paddingLarge

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = stringResource(R.string.profile_title),
                        style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                    )
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .wrapContentWidth(Alignment.CenterHorizontally)
                .widthIn(max = contentMaxWidth)
                .verticalScroll(rememberScrollState())
        ) {
            // Profile header
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = horizontalPad, vertical = TaBritaDimens.paddingLarge),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Box(
                    modifier = Modifier
                        .size(avatarSize)
                        .clip(CircleShape)
                        .background(MaterialTheme.colorScheme.primary),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(
                        imageVector = Icons.Default.Person,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.onPrimary,
                        modifier = Modifier.size(if (isExpanded) TaBritaDimens.avatarIconSizeLarge else TaBritaDimens.avatarIconSize)
                    )
                }

                Spacer(modifier = Modifier.height(TaBritaDimens.paddingMedium))

                Text(
                    text = stringResource(R.string.profile_reader_title),
                    style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold)
                )
                Text(
                    text = stringResource(R.string.profile_email_placeholder),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            Spacer(modifier = Modifier.height(TaBritaDimens.paddingXSmall))

            // Settings Section
            SettingsItem(
                icon = Icons.Default.DarkMode,
                title = stringResource(R.string.profile_dark_theme),
                subtitle = stringResource(R.string.profile_dark_theme_sub),
                trailing = {
                    Switch(
                        checked = isDarkMode,
                        onCheckedChange = { isDarkMode = it }
                    )
                },
                horizontalPadding = horizontalPad
            )

            SettingsItem(
                icon = Icons.Default.Notifications,
                title = stringResource(R.string.profile_notifications_title),
                subtitle = stringResource(R.string.profile_notifications_sub),
                trailing = {
                    Switch(
                        checked = notificationsEnabled,
                        onCheckedChange = { notificationsEnabled = it }
                    )
                },
                horizontalPadding = horizontalPad
            )

            HorizontalDivider(
                modifier = Modifier.padding(horizontal = horizontalPad, vertical = TaBritaDimens.paddingXSmall),
                color = MaterialTheme.colorScheme.outline.copy(alpha = 0.4f)
            )

            SettingsItem(
                icon = Icons.Default.Info,
                title = stringResource(R.string.profile_about_title),
                subtitle = stringResource(R.string.profile_about_sub, APP_VERSION),
                trailing = {
                    Icon(
                        imageVector = Icons.Default.ChevronRight,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                },
                onClick = { /* TODO: open about */ },
                horizontalPadding = horizontalPad
            )

            Spacer(modifier = Modifier.height(TaBritaDimens.paddingXXLarge))

            // Logout mock
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = horizontalPad)
                    .clip(RoundedCornerShape(TaBritaDimens.cornerLarge))
                    .background(MaterialTheme.colorScheme.surface)
                    .clickable { /* mock */ }
                    .padding(TaBritaDimens.paddingMedium),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = stringResource(R.string.profile_logout_text),
                    style = MaterialTheme.typography.labelLarge,
                    color = MaterialTheme.colorScheme.error
                )
            }

            Spacer(modifier = Modifier.height(TaBritaDimens.paddingXXLarge))
        }
    }
}

@Composable
private fun SettingsItem(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    title: String,
    subtitle: String,
    trailing: @Composable () -> Unit,
    onClick: (() -> Unit)? = null,
    horizontalPadding: androidx.compose.ui.unit.Dp = TaBritaDimens.paddingLarge
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(enabled = onClick != null, onClick = { onClick?.invoke() })
            .padding(horizontal = horizontalPadding, vertical = TaBritaDimens.paddingSmall),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = MaterialTheme.colorScheme.primary,
            modifier = Modifier.size(TaBritaDimens.iconSizeMedium)
        )

        Spacer(modifier = Modifier.width(TaBritaDimens.paddingMedium))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = title,
                style = MaterialTheme.typography.titleMedium
            )
            Text(
                text = subtitle,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        trailing()
    }
}

